### PR TITLE
Minor fix.

### PR DESCRIPTION
**Pull request by revit13**
Signed-off-by: Revital Sur <eres@il.ibm.com>

### CODE REVIEW

**Comment by roytman** [comment]
Can you update the compatibility matrix in the README file

**Comment by revit13** [comment]
@roytman this is for release 0.5.0 -- the readme is updated.

**Comment by roytman** [comment]
> 

I meant for 0.6.0

**Comment by revit13** [comment]
@roytman ok I planned to add it with the 0.6.0 updates which should be after 0.5.0 is released....

**Review by roytman — APPROVED** [review]

**Pull request merged**
